/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IContract  {
    function supportsInterface(bytes4 _interface) external view returns (bool);

    function mint(address to) external;

    function symbol() external view returns (string memory);

    function name() external view returns (string memory);

    function description() external view returns (string memory);

    function balanceOf(address owner) external view returns (uint256);

    function ownerOf(uint256 token_id) external view returns (address);

    function chooseMove() external view returns (uint32);

    function updateQValue(uint32 player_move, int32 reward) external;

    function play(uint32 player_move) external returns (uint32, int32);

    function getHistory() external view returns (int32[5] memory);

    function tokenURI(uint256 token_id) external view returns (string memory);
}
